/**
 * Local inference utilities for the ML platform.
 *
 * Current behavior:
 * - If a trained model checkpoint exists for the project, load it and run inference.
 * - Otherwise, fall back to a lightweight local text generator so the sandbox
 *   still produces platform-generated output instead of external API calls.
 *
 * This keeps the runtime self-contained and makes it straightforward to plug
 * in real trained models later.
 */

const MODEL_CACHE = new Map<string, unknown>();

export async function generateLocalResponse(prompt: string, projectId: string): Promise<string> {
  const trimmed = prompt.trim();
  if (!trimmed) {
    return 'Please enter a prompt to generate a response.';
  }

  const model = await loadProjectModel(projectId);
  if (model && typeof (model as { predict?: (input: string) => Promise<string> }).predict === 'function') {
    try {
      const result = await (model as { predict: (input: string) => Promise<string> }).predict(trimmed);
      if (typeof result === 'string' && result.trim().length > 0) {
        return result;
      }
    } catch (error) {
      console.error('Local model inference failed, falling back to generator.', error);
    }
  }

  return generateFallbackResponse(trimmed);
}

async function loadProjectModel(projectId: string): Promise<unknown> {
  const cached = MODEL_CACHE.get(projectId);
  if (cached) {
    return cached;
  }

  try {
    const { default: tf } = await import('@tensorflow/tfjs');
    const modelUrl = `/api/checkpoints/download?projectId=${encodeURIComponent(projectId)}`;
    const model = await tf.loadLayersModel(modelUrl);
    MODEL_CACHE.set(projectId, model);
    return model;
  } catch (error) {
    console.warn('No trained model found for project, using fallback generator.', error);
    return null;
  }
}

function generateFallbackResponse(prompt: string): string {
  const lower = prompt.toLowerCase();
  const greetingMatch = lower.match(/^(hi|hello|hey|greetings|howdy|yo)[\s!,.]*/i);

  if (greetingMatch || lower === 'hi' || lower === 'hello') {
    return `Hello! I'm your local ML assistant. You said: "${prompt}". I'm ready to help with your project.`;
  }

  if (lower.includes('help')) {
    return `Here is some help for: "${prompt}". This platform supports local model training and inference.`;
  }

  if (lower.includes('code') || lower.includes('function') || lower.includes('program')) {
    return `Here is a code example based on your request: "${prompt}".\n\nfunction example() {\n  return 'Hello from local inference';\n}`;
  }

  if (lower.includes('explain') || lower.includes('what is')) {
    return `Let me explain: "${prompt}". This is a locally generated response from the ML platform's inference engine.`;
  }

  const words = prompt.split(/\s+/).slice(0, 6).join(' ');
  return `Processed locally: "${words}". This response was generated by the platform's local inference system.`;
}
