'use client';

import React, { useEffect, useState, useMemo } from 'react';
import { useRouter } from 'next/navigation';
import { usePipelineStore } from '../../store/usePipelineStore';
import { 
  BookOpen, 
  Database, 
  Cpu, 
  PlayCircle, 
  Terminal, 
  Compass,
  ArrowRight,
  Download,
  Copy,
  Check,
  FileCode,
  LayoutTemplate,
  Info,
  Layers,
  Code
} from 'lucide-react';

export default function DocsPage() {
  const { currentProject, etl, modelConfig } = usePipelineStore();
  const router = useRouter();
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (!currentProject) {
      router.push('/');
    }
  }, [currentProject, router]);

  const classNames = etl.classNames || ['Cat', 'Dog', 'Bird'];
  const layers = modelConfig.layers;
  const hp = modelConfig.hyperparameters;

  // Autogenerate TensorFlow/Keras training script code
  const tensorflowScript = useMemo(() => {
    let tfLayers = '';

    layers.forEach((layer, i) => {
      const cfg = layer.config;
      if (layer.type === 'conv2d') {
        tfLayers += `    layers.Conv2D(filters=${cfg.filters || 32}, kernel_size=${cfg.kernelSize || 3}, padding='${cfg.padding || 'same'}', strides=${cfg.strides || 1}, activation='${cfg.activation || 'relu'}'),\n`;
        tfLayers += `    layers.BatchNormalization(),\n`;
        if (cfg.dropout && cfg.dropout > 0) {
          tfLayers += `    layers.Dropout(${cfg.dropout}),\n`;
        }
      } else if (layer.type === 'maxPooling2d') {
        tfLayers += `    layers.MaxPooling2D(pool_size=${cfg.poolSize || 2}, strides=${cfg.strides || 2}),\n`;
      } else if (layer.type === 'flatten') {
        tfLayers += `    layers.Flatten(),\n`;
      } else if (layer.type === 'dense') {
        tfLayers += `    layers.Dense(units=${cfg.units || 64}, activation='${cfg.activation || 'relu'}'),\n`;
        if (cfg.dropout && cfg.dropout > 0) {
          tfLayers += `    layers.Dropout(${cfg.dropout}),\n`;
        }
      } else if (layer.type === 'dropout') {
        tfLayers += `    layers.Dropout(${cfg.rate || 0.25}),\n`;
      } else if (layer.type === 'batchNorm') {
        tfLayers += `    layers.BatchNormalization(momentum=${cfg.momentum || 0.99}, epsilon=${cfg.epsilon || 0.001}),\n`;
      } else if (layer.type === 'embedding') {
        tfLayers += `    layers.Embedding(input_dim=${cfg.inputDim || 5000}, output_dim=${cfg.outputDim || 128}, input_length=${cfg.inputLength || 100}),\n`;
      } else if (layer.type === 'lstm') {
        tfLayers += `    layers.LSTM(units=${cfg.units || 64}, return_sequences=${cfg.returnSequences ? 'True' : 'False'}, dropout=${cfg.dropout || 0}, recurrent_dropout=${cfg.recurrentDropout || 0}),\n`;
      } else if (layer.type === 'gru') {
        tfLayers += `    layers.GRU(units=${cfg.units || 64}, return_sequences=${cfg.returnSequences ? 'True' : 'False'}, dropout=${cfg.dropout || 0}),\n`;
      } else if (layer.type === 'bidirectional') {
        tfLayers += `    layers.Bidirectional(layers.LSTM(units=${cfg.units || 64}, return_sequences=${cfg.returnSequences ? 'True' : 'False'})),\n`;
      }
    });

    const lossMap: Record<string, string> = {
      categoricalCrossentropy: "losses.CategoricalCrossentropy()",
      meanSquaredError: "losses.MeanSquaredError()",
      binaryCrossentropy: "losses.BinaryCrossentropy()",
      sparseCategoricalCrossentropy: "losses.SparseCategoricalCrossentropy()"
    };

    const optMap: Record<string, string> = {
      adam: "optimizers.Adam",
      sgd: "optimizers.SGD",
      rmsprop: "optimizers.RMSprop"
    };

    const etlActions = (etl.actions || [])
      .filter(a => a.enabled)
      .map(a => `#  - ${a.type.toUpperCase()} (params: ${JSON.stringify(a.params)})`)
      .join('\n');

    return `# ==========================================
# TENSORFLOW / KERAS AUTOGENERATED WORKFLOW
# Generated by xMachine Telemetry Engine
# ==========================================

import tensorflow as tf
from tensorflow.keras import layers, models, optimizers, losses, callbacks
import numpy as np

# 1. Dataset ETL & Split Configuration
# ------------------------------------------
# Ingestion Format: ${etl.files.length > 0 ? etl.files[0].type.toUpperCase() : 'STANDARD'}
# Total Files: ${etl.files.length}
# Train Split: ${etl.splitRatio?.train || 80}%
# Validation Split: ${etl.splitRatio?.val || 20}%
# Test Split: ${etl.splitRatio?.test || 0}%
# Batch Size: ${etl.batchSize || 32}
# Shuffle: ${etl.shuffle ? 'True' : 'False'}
# Stratified: ${etl.stratified ? 'True' : 'False'}
# Random Seed: ${etl.seed || 42}
#
# Transforms pipelines configured:
${etlActions || '#  - No active transformations configured.'}

# Set random seed for reproducibility
tf.random.set_seed(${etl.seed || 42})
np.random.seed(${etl.seed || 42})

# 2. Model Architecture definition
def build_model(input_shape=(224, 224, 3), num_classes=${classNames.length}):
    model = models.Sequential([
        # Input layer mapping domain specification
        layers.Input(shape=input_shape),
        
        # Layer stack from Model Builder
${tfLayers || '        layers.Identity(),\n'}
        # Output dense classification layer matching target classes
        layers.Dense(num_classes, activation='softmax' if num_classes > 2 else 'sigmoid')
    ])
    return model

model = build_model()
model.summary()

# 3. Optimization and Compilation
optimizer = ${optMap[hp.optimizer] || 'optimizers.Adam'}(learning_rate=${hp.learningRate})
loss_fn = ${lossMap[hp.loss] || 'losses.CategoricalCrossentropy()'}

model.compile(
    optimizer=optimizer,
    loss=loss_fn,
    metrics=['accuracy']
)

# 4. Training Callbacks Configuration
training_callbacks = []

# Learning Rate Scheduler simulation
# LR Scheduler type: Cosine/Step
training_callbacks.append(callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3))

# Early Stopping callback
training_callbacks.append(
    callbacks.EarlyStopping(
        monitor='val_loss', 
        patience=5, 
        restore_best_weights=True
    )
)

# 5. Pipeline Run Execution
# mock dataset pipeline
train_x = np.random.randn(256, 224, 224, 3)
train_y = np.random.randint(0, ${classNames.length}, size=(256,))
val_x = np.random.randn(64, 224, 224, 3)
val_y = np.random.randint(0, ${classNames.length}, size=(64,))

if ${classNames.length} > 2:
    train_y = tf.one_hot(train_y, ${classNames.length})
    val_y = tf.one_hot(val_y, ${classNames.length})

print("Executing TensorFlow/Keras training workflow...")
history = model.fit(
    train_x, train_y,
    validation_data=(val_x, val_y),
    batch_size=${etl.batchSize || 32},
    epochs=${hp.epochs},
    callbacks=training_callbacks,
    shuffle=${etl.shuffle ? 'True' : 'False'}
)
`;
  }, [layers, hp, classNames, etl]);

  // Generate ipynb file content
  const notebookJson = useMemo(() => {
    const cells = [
      {
        cell_type: 'markdown',
        metadata: {},
        source: [
          `# TensorFlow/Keras Workflow Notebook: ${currentProject?.name || 'Untitled'}\n`,
          `This notebook maps out the pipeline, ETL config, and custom architecture compiled inside **xMachine**.\n`,
          `* **Project Domain:** \`${currentProject?.domain}\`\n`,
          `* **Target Classes:** \`${classNames.join(', ')}\`\n`,
          `* **Ingested files:** \`${etl.files.length} items\`\n`
        ]
      },
      {
        cell_type: 'markdown',
        metadata: {},
        source: [
          `## 1. Imports and Setup\n`,
          `We begin by importing standard TensorFlow and Keras libraries.`
        ]
      },
      {
        cell_type: 'code',
        execution_count: null,
        metadata: {},
        outputs: [],
        source: [
          `import tensorflow as tf\n`,
          `from tensorflow.keras import layers, models, optimizers, losses, callbacks\n`,
          `import numpy as np\n\n`,
          `print(f"TensorFlow version: {tf.__version__}")\n`,
          `print(f"GPUs Available: {tf.config.list_physical_devices('GPU')}")`
        ]
      },
      {
        cell_type: 'markdown',
        metadata: {},
        source: [
          `## 2. Dynamic Model Architecture\n`,
          `The architecture below is compiled based on the stack created inside the model builder.`
        ]
      },
      {
        cell_type: 'code',
        execution_count: null,
        metadata: {},
        outputs: [],
        source: [
          tensorflowScript.split('\n').filter(line => !line.startsWith('import ') && !line.startsWith('# =') && !line.startsWith('# Generated')).map(l => l + '\n')
        ]
      }
    ];

    return JSON.stringify({
      cells,
      metadata: {
        kernelspec: {
          display_name: 'Python 3',
          language: 'python',
          name: 'python3'
        },
        language_info: {
          name: 'python'
        }
      },
      nbformat: 4,
      nbformat_minor: 2
    }, null, 2);
  }, [currentProject, classNames, etl, tensorflowScript]);

  const downloadFile = (content: string, fileName: string, contentType: string) => {
    const blob = new Blob([content], { type: contentType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = fileName;
    link.click();
    URL.revokeObjectURL(url);
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(tensorflowScript);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (!currentProject) return null;

  return (
    <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 pt-4 sm:pt-8 pb-16 text-left">
      <div className="bg-neutral-50 dark:bg-neutral-900 rounded-2xl p-4 sm:p-6 sm:p-8 space-y-6 sm:space-y-8 shadow-sm">
        
        {/* Title */}
        <div className="flex items-center gap-3 pb-6 border-b border-neutral-200 dark:border-neutral-800">
          <div className="p-3 bg-royalblue-500/10 rounded-xl">
            <BookOpen className="w-6 h-6 text-royalblue-600 dark:text-royalblue-400" />
          </div>
          <div>
            <h1 className="text-lg sm:text-2xl font-black text-neutral-900 dark:text-white uppercase tracking-wider">Workspace User Manual</h1>
            <p className="text-xs text-neutral-500 dark:text-neutral-400">Comprehensive instructions, workflow lifecycle, and code export templates.</p>
          </div>
        </div>

        {/* Platform Overview */}
        <div className="space-y-4">
          <h2 className="text-sm font-bold text-neutral-900 dark:text-white uppercase tracking-wider flex items-center gap-2">
            <Compass className="w-4 h-4 text-royalblue-500" />
            <span>Platform Lifecycle &amp; How It Works</span>
          </h2>
          <p className="text-xs text-neutral-600 dark:text-neutral-400 leading-relaxed">
            ML-Studio-Web is an end-to-end interactive platform for designing, preparing, training, and evaluating deep learning models client-side in the browser, powered by a secure Mongoose/MongoDB backend. 
            The workspace workflow consists of five key phases:
          </p>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-2">
            <div className="p-4 rounded-xl bg-white dark:bg-neutral-950 border border-neutral-100 dark:border-neutral-900 space-y-2">
              <div className="flex items-center gap-2 text-xs font-bold text-neutral-800 dark:text-neutral-200">
                <Database className="w-4 h-4 text-royalblue-500" />
                <span>1. Data Ingestion &amp; ETL</span>
              </div>
              <p className="text-[11px] text-neutral-500 dark:text-neutral-400 leading-relaxed">
                Upload image assets, text corpora, or spreadsheets. Choose dataset partitioning (Train / Val / Test) and add cleaning/augmentation steps (Resizing, Tokenization, Normalization) that are automatically cached.
              </p>
            </div>

            <div className="p-4 rounded-xl bg-white dark:bg-neutral-950 border border-neutral-100 dark:border-neutral-900 space-y-2">
              <div className="flex items-center gap-2 text-xs font-bold text-neutral-800 dark:text-neutral-200">
                <Cpu className="w-4 h-4 text-royalblue-500" />
                <span>2. Model Builder</span>
              </div>
              <p className="text-[11px] text-neutral-500 dark:text-neutral-400 leading-relaxed">
                Architect layers interactively. Stack convolution, pooling, batchnorm, dropout, or recurrent modules (LSTM/GRU). Parameters like filters, units, and activation functions are automatically checked and configured.
              </p>
            </div>

            <div className="p-4 rounded-xl bg-white dark:bg-neutral-950 border border-neutral-100 dark:border-neutral-900 space-y-2">
              <div className="flex items-center gap-2 text-xs font-bold text-neutral-800 dark:text-neutral-200">
                <PlayCircle className="w-4 h-4 text-royalblue-500" />
                <span>3. Live Telemetry Engine</span>
              </div>
              <p className="text-[11px] text-neutral-500 dark:text-neutral-400 leading-relaxed">
                Simulate training with advanced parameters (AMP precision, GPU accelerators, Cosine lr decay). Observe real-time training charts and console terminal outputs, with checkpoints saved automatically to MongoDB.
              </p>
            </div>

            <div className="p-4 rounded-xl bg-white dark:bg-neutral-950 border border-neutral-100 dark:border-neutral-900 space-y-2">
              <div className="flex items-center gap-2 text-xs font-bold text-neutral-800 dark:text-neutral-200">
                <Terminal className="w-4 h-4 text-royalblue-500" />
                <span>4. Inference Sandbox</span>
              </div>
              <p className="text-[11px] text-neutral-500 dark:text-neutral-400 leading-relaxed">
                Test model performance using single-item inputs or run bulk evaluation partitions to dynamically compute classification reports, precision/recall stats, and visual confusion matrix heatmaps.
              </p>
            </div>
          </div>
        </div>

        {/* Dynamic Extract Code Section */}
        <div className="pt-6 border-t border-neutral-200 dark:border-neutral-800 space-y-5">
          <div className="space-y-1">
            <h2 className="text-sm font-bold text-neutral-900 dark:text-white uppercase tracking-wider flex items-center gap-2">
              <FileCode className="w-4 h-4 text-royalblue-500" />
              <span>Extract Code &amp; Export Notebook</span>
            </h2>
            <p className="text-xs text-neutral-500 dark:text-neutral-400">
              Download structured code configurations directly matching your active project parameters to run and scale training on high-performance local clusters or cloud instances.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Jupyter Notebook Card */}
            <div className="bg-white dark:bg-neutral-950 rounded-xl p-5 border border-neutral-150 dark:border-neutral-900 shadow-sm flex flex-col justify-between space-y-4 text-left">
              <div className="space-y-2">
                <div className="flex items-center gap-2">
                  <LayoutTemplate className="w-5 h-5 text-royalblue-500" />
                  <h3 className="text-xs font-bold text-neutral-800 dark:text-neutral-200 uppercase tracking-wider">Jupyter Notebook (.ipynb)</h3>
                </div>
                <p className="text-[11px] text-neutral-500 dark:text-neutral-400 leading-relaxed">
                  Export an interactive notebook containing step-by-step markdown explanations, training loop cell, TensorFlow dataset loaders, and model definitions configured in your builder.
                </p>
              </div>
              <button
                onClick={() => downloadFile(notebookJson, `${currentProject.name.toLowerCase().replace(/\s+/g, '_')}_pipeline.ipynb`, 'application/json')}
                className="w-full py-2.5 bg-royalblue-600 hover:bg-royalblue-500 text-white rounded-lg flex items-center justify-center gap-1.5 text-xs font-bold transition-all shadow-sm"
              >
                <Download className="w-3.5 h-3.5" />
                <span>Download Notebook (.ipynb)</span>
              </button>
            </div>

            {/* Python Code Script Card */}
            <div className="bg-white dark:bg-neutral-950 rounded-xl p-5 border border-neutral-150 dark:border-neutral-900 shadow-sm flex flex-col justify-between space-y-4 text-left">
              <div className="space-y-2">
                <div className="flex items-center gap-2">
                  <Code className="w-5 h-5 text-emerald-500" />
                  <h3 className="text-xs font-bold text-neutral-800 dark:text-neutral-200 uppercase tracking-wider">Standalone Python Script (.py)</h3>
                </div>
                <p className="text-[11px] text-neutral-500 dark:text-neutral-400 leading-relaxed">
                  Download a production-grade Python script mapping out the full TensorFlow/Keras transformations, learning rate schedulers, model compile specifications, and optimization pipelines.
                </p>
              </div>
              <div className="flex gap-2">
                <button
                  onClick={copyToClipboard}
                  className="flex-1 py-2.5 bg-neutral-100 dark:bg-neutral-900 hover:bg-neutral-200 dark:hover:bg-neutral-800 text-neutral-700 dark:text-neutral-300 rounded-lg flex items-center justify-center gap-1.5 text-xs font-semibold transition-all border border-neutral-200 dark:border-neutral-800"
                >
                  {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                  <span>{copied ? 'Copied!' : 'Copy Script'}</span>
                </button>
                <button
                  onClick={() => downloadFile(tensorflowScript, `${currentProject.name.toLowerCase().replace(/\s+/g, '_')}_train.py`, 'text/plain')}
                  className="py-2.5 px-4 bg-royalblue-600 hover:bg-royalblue-500 text-white rounded-lg flex items-center justify-center gap-1.5 text-xs font-bold transition-all shadow-sm"
                  title="Download Python Script"
                >
                  <Download className="w-3.5 h-3.5" />
                </button>
              </div>
            </div>
          </div>
        </div>

        {/* Footer Navigation */}
        <div className="pt-6 flex flex-wrap justify-end gap-3 border-t border-neutral-200 dark:border-neutral-800">
          <button
            onClick={() => router.push('/etl')}
            className="flex items-center gap-2 px-4 py-2.5 bg-royalblue-600 hover:bg-royalblue-500 text-white rounded-lg text-xs font-semibold transition-all group shadow-sm"
          >
            <span>Proceed to Ingestion</span>
            <ArrowRight className="w-3.5 h-3.5 transition-transform group-hover:translate-x-1" />
          </button>
        </div>

      </div>
    </div>
  );
}
