'use client';

import React, { useEffect, useState, useMemo } from 'react';
import { useRouter } from 'next/navigation';
import { usePipelineStore } from '../../store/usePipelineStore';
import { 
  BookOpen, 
  Database, 
  Cpu, 
  PlayCircle, 
  Terminal, 
  Compass,
  ArrowRight,
  Download,
  Copy,
  Check,
  FileCode,
  LayoutTemplate,
  Info,
  Layers,
  Code
} from 'lucide-react';

export default function DocsPage() {
  const { currentProject, etl, modelConfig } = usePipelineStore();
  const router = useRouter();
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (!currentProject) {
      router.push('/');
    }
  }, [currentProject, router]);

  const classNames = etl.classNames || ['Cat', 'Dog', 'Bird'];
  const layers = modelConfig.layers;
  const hp = modelConfig.hyperparameters;

  // Autogenerate PyTorch training script code
  const pytorchScript = useMemo(() => {
    let pyLayers = '';
    let flatDimCalculated = false;

    layers.forEach((layer, i) => {
      const cfg = layer.config;
      if (layer.type === 'conv2d') {
        pyLayers += `        self.layer_${i} = nn.Sequential(\n`;
        pyLayers += `            nn.Conv2d(${i === 0 ? '3' : 'prev_channels'}, ${cfg.filters || 32}, kernel_size=${cfg.kernelSize || 3}, padding='${cfg.padding || 'same'}', stride=${cfg.strides || 1}),\n`;
        pyLayers += `            nn.BatchNorm2d(${cfg.filters || 32}),\n`;
        pyLayers += `            nn.ReLU(),\n`;
        if (cfg.dropout && cfg.dropout > 0) {
          pyLayers += `            nn.Dropout2d(p=${cfg.dropout}),\n`;
        }
        pyLayers += `        )\n`;
      } else if (layer.type === 'maxPooling2d') {
        pyLayers += `        self.layer_${i} = nn.MaxPool2d(kernel_size=${cfg.poolSize || 2}, stride=${cfg.strides || 2})\n`;
      } else if (layer.type === 'flatten') {
        pyLayers += `        self.layer_${i} = nn.Flatten()\n`;
        flatDimCalculated = true;
      } else if (layer.type === 'dense') {
        pyLayers += `        self.layer_${i} = nn.Sequential(\n`;
        pyLayers += `            nn.Linear(${!flatDimCalculated ? '512' : 'flat_features'}, ${cfg.units || 64}),\n`;
        pyLayers += `            nn.ReLU(),\n`;
        if (cfg.dropout && cfg.dropout > 0) {
          pyLayers += `            nn.Dropout(p=${cfg.dropout}),\n`;
        }
        pyLayers += `        )\n`;
      } else if (layer.type === 'dropout') {
        pyLayers += `        self.layer_${i} = nn.Dropout(p=${cfg.rate || 0.25})\n`;
      } else if (layer.type === 'batchNorm') {
        pyLayers += `        self.layer_${i} = nn.BatchNorm1d(${cfg.numFeatures || 64}, momentum=${cfg.momentum || 0.1})\n`;
      } else if (layer.type === 'embedding') {
        pyLayers += `        self.layer_${i} = nn.Embedding(${cfg.inputDim || 5000}, ${cfg.outputDim || 128})\n`;
      } else if (layer.type === 'lstm') {
        pyLayers += `        self.layer_${i} = nn.LSTM(${i === 0 ? 'input_dim' : 'prev_dim'}, ${cfg.units || 64}, batch_first=True, dropout=${cfg.dropout || 0})\n`;
      } else if (layer.type === 'gru') {
        pyLayers += `        self.layer_${i} = nn.GRU(${i === 0 ? 'input_dim' : 'prev_dim'}, ${cfg.units || 64}, batch_first=True, dropout=${cfg.dropout || 0})\n`;
      } else if (layer.type === 'bidirectional') {
        pyLayers += `        self.layer_${i} = nn.Bidirectional(nn.LSTM(${i === 0 ? 'input_dim' : 'prev_dim'}, ${cfg.units || 64}, batch_first=True))\n`;
      }
    });

    const lossMap: Record<string, string> = {
      categoricalCrossentropy: 'nn.CrossEntropyLoss()',
      meanSquaredError: 'nn.MSELoss()',
      binaryCrossentropy: 'nn.BCELoss()',
      sparseCategoricalCrossentropy: 'nn.CrossEntropyLoss()'
    };

    const optMap: Record<string, string> = {
      adam: 'optim.Adam',
      sgd: 'optim.SGD',
      rmsprop: 'optim.RMSprop'
    };

    return `# ==========================================
# PYTORCH AUTOGENERATED TRAINING SCRIPT
# Generated by xMachine Live Telemetry Engine
# ==========================================

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

# 1. Device Configuration
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Training using device: {device}")

# 2. Model Architecture definition
class CustomModel(nn.Module):
    def __init__(self, input_dim=3, flat_features=512, num_classes=${classNames.length}):
        super(CustomModel, self).__init__()
        
        # Sequentially constructed layers from model builder
${pyLayers || '        self.features = nn.Identity()'}
        # Output layer matching classes
        self.output_layer = nn.Linear(${layers.length > 0 ? '64' : 'input_dim'}, num_classes)

    def forward(self, x):
        # Forward pass workflow
        for layer in [attr for attr in dir(self) if attr.startswith('layer_')]:
            x = getattr(self, layer)(x)
        return self.output_layer(x)

# 3. Model initialization
model = CustomModel().to(device)

# 4. Loss & Optimizer configuration
criterion = ${lossMap[hp.loss] || 'nn.CrossEntropyLoss()'}
optimizer = ${optMap[hp.optimizer] || 'optim.Adam'}(model.parameters(), lr=${hp.learningRate})

# 5. Training Loop
def train(model, dataloader, epochs=${hp.epochs}):
    model.train()
    for epoch in range(epochs):
        running_loss = 0.0
        correct = 0
        total = 0
        
        for inputs, targets in dataloader:
            inputs, targets = inputs.to(device), targets.to(device)
            optimizer.zero_grad()
            
            # Forward pass
            outputs = model(inputs)
            loss = criterion(outputs, targets)
            
            # Backward pass
            loss.backward()
            optimizer.step()
            
            running_loss += loss.item() * inputs.size(0)
            _, predicted = outputs.max(1)
            total += targets.size(0)
            correct += predicted.eq(targets).sum().item()
            
        epoch_loss = running_loss / len(dataloader.dataset)
        epoch_acc = correct / total
        print(f"Epoch {epoch+1}/{epochs} - loss: {epoch_loss:.4f} - acc: {epoch_acc:.4f}")

print("PyTorch model ready for scaling!")
`;
  }, [layers, hp, classNames]);

  // Generate ipynb file content
  const notebookJson = useMemo(() => {
    const cells = [
      {
        cell_type: 'markdown',
        metadata: {},
        source: [
          `# Project Notebook: ${currentProject?.name || 'Untitled'}\n`,
          `This notebook maps out the pipeline, ETL config, and custom architecture compiled inside **xMachine**.\n`,
          `* **Project Domain:** \`${currentProject?.domain}\`\n`,
          `* **Target Classes:** \`${classNames.join(', ')}\`\n`,
          `* **Ingested files:** \`${etl.files.length} items\`\n`
        ]
      },
      {
        cell_type: 'markdown',
        metadata: {},
        source: [
          `## 1. Imports and Setup\n`,
          `We begin by importing standard Pytorch components and configuring GPU acceleration.`
        ]
      },
      {
        cell_type: 'code',
        execution_count: null,
        metadata: {},
        outputs: [],
        source: [
          `import torch\n`,
          `import torch.nn as nn\n`,
          `import torch.optim as optim\n`,
          `from torch.utils.data import DataLoader, TensorDataset\n`,
          `import numpy as np\n\n`,
          `device = torch.device("cuda" if torch.cuda.is_available() else "cpu")\n`,
          `print(f"Executing on device: {device}")`
        ]
      },
      {
        cell_type: 'markdown',
        metadata: {},
        source: [
          `## 2. Dynamic Model Architecture\n`,
          `The architecture below is compiled based on the stack created inside the model builder.`
        ]
      },
      {
        cell_type: 'code',
        execution_count: null,
        metadata: {},
        outputs: [],
        source: [
          pytorchScript.split('\n').filter(line => !line.startsWith('import ') && !line.startsWith('# =') && !line.startsWith('# Generated')).map(l => l + '\n')
        ]
      },
      {
        cell_type: 'markdown',
        metadata: {},
        source: [
          `## 3. Training and Evaluation Pipeline\n`,
          `Run the fitting loops to train the model weight tensors.`
        ]
      },
      {
        cell_type: 'code',
        execution_count: null,
        metadata: {},
        outputs: [],
        source: [
          `# Mocking DataLoader tensors matching batch size\n`,
          `dummy_features = torch.randn(128, 3, 224, 224) if "${currentProject?.domain}".startswith("cv") else torch.randn(128, 100)\n`,
          `dummy_targets = torch.randint(0, ${classNames.length}, (128,))\n`,
          `dataset = TensorDataset(dummy_features, dummy_targets)\n`,
          `dataloader = DataLoader(dataset, batch_size=${hp.batchSize}, shuffle=True)\n\n`,
          `# Running execution loop\n`,
          `train(model, dataloader, epochs=${hp.epochs})`
        ]
      }
    ];

    return JSON.stringify({
      cells,
      metadata: {
        kernelspec: {
          display_name: 'Python 3',
          language: 'python',
          name: 'python3'
        },
        language_info: {
          name: 'python'
        }
      },
      nbformat: 4,
      nbformat_minor: 2
    }, null, 2);
  }, [currentProject, classNames, etl, hp, pytorchScript]);

  const downloadFile = (content: string, fileName: string, contentType: string) => {
    const blob = new Blob([content], { type: contentType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = fileName;
    link.click();
    URL.revokeObjectURL(url);
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(pytorchScript);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (!currentProject) return null;

  return (
    <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 pt-8 pb-16 text-left">
      <div className="bg-neutral-50 dark:bg-neutral-900 rounded-2xl p-6 sm:p-8 space-y-8 shadow-sm">
        
        {/* Title */}
        <div className="flex items-center gap-3 pb-6 border-b border-neutral-200 dark:border-neutral-800">
          <div className="p-3 bg-royalblue-500/10 rounded-xl">
            <BookOpen className="w-6 h-6 text-royalblue-600 dark:text-royalblue-400" />
          </div>
          <div>
            <h1 className="text-2xl font-black text-neutral-900 dark:text-white uppercase tracking-wider">Workspace User Manual</h1>
            <p className="text-xs text-neutral-500 dark:text-neutral-400">Comprehensive instructions, workflow lifecycle, and code export templates.</p>
          </div>
        </div>

        {/* Platform Overview */}
        <div className="space-y-4">
          <h2 className="text-sm font-bold text-neutral-900 dark:text-white uppercase tracking-wider flex items-center gap-2">
            <Compass className="w-4 h-4 text-royalblue-500" />
            <span>Platform Lifecycle &amp; How It Works</span>
          </h2>
          <p className="text-xs text-neutral-600 dark:text-neutral-400 leading-relaxed">
            ML-Studio-Web is an end-to-end interactive platform for designing, preparing, training, and evaluating deep learning models client-side in the browser, powered by a secure Mongoose/MongoDB backend. 
            The workspace workflow consists of five key phases:
          </p>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-2">
            <div className="p-4 rounded-xl bg-white dark:bg-neutral-950 border border-neutral-100 dark:border-neutral-900 space-y-2">
              <div className="flex items-center gap-2 text-xs font-bold text-neutral-800 dark:text-neutral-200">
                <Database className="w-4 h-4 text-royalblue-500" />
                <span>1. Data Ingestion &amp; ETL</span>
              </div>
              <p className="text-[11px] text-neutral-500 dark:text-neutral-400 leading-relaxed">
                Upload image assets, text corpora, or spreadsheets. Choose dataset partitioning (Train / Val / Test) and add cleaning/augmentation steps (Resizing, Tokenization, Normalization) that are automatically cached.
              </p>
            </div>

            <div className="p-4 rounded-xl bg-white dark:bg-neutral-950 border border-neutral-100 dark:border-neutral-900 space-y-2">
              <div className="flex items-center gap-2 text-xs font-bold text-neutral-800 dark:text-neutral-200">
                <Cpu className="w-4 h-4 text-royalblue-500" />
                <span>2. Model Builder</span>
              </div>
              <p className="text-[11px] text-neutral-500 dark:text-neutral-400 leading-relaxed">
                Architect layers interactively. Stack convolution, pooling, batchnorm, dropout, or recurrent modules (LSTM/GRU). Parameters like filters, units, and activation functions are automatically checked and configured.
              </p>
            </div>

            <div className="p-4 rounded-xl bg-white dark:bg-neutral-950 border border-neutral-100 dark:border-neutral-900 space-y-2">
              <div className="flex items-center gap-2 text-xs font-bold text-neutral-800 dark:text-neutral-200">
                <PlayCircle className="w-4 h-4 text-royalblue-500" />
                <span>3. Live Telemetry Engine</span>
              </div>
              <p className="text-[11px] text-neutral-500 dark:text-neutral-400 leading-relaxed">
                Simulate training with advanced parameters (AMP precision, GPU accelerators, Cosine lr decay). Observe real-time training charts and console terminal outputs, with checkpoints saved automatically to MongoDB.
              </p>
            </div>

            <div className="p-4 rounded-xl bg-white dark:bg-neutral-950 border border-neutral-100 dark:border-neutral-900 space-y-2">
              <div className="flex items-center gap-2 text-xs font-bold text-neutral-800 dark:text-neutral-200">
                <Terminal className="w-4 h-4 text-royalblue-500" />
                <span>4. Inference Sandbox</span>
              </div>
              <p className="text-[11px] text-neutral-500 dark:text-neutral-400 leading-relaxed">
                Test model performance using single-item inputs or run bulk evaluation partitions to dynamically compute classification reports, precision/recall stats, and visual confusion matrix heatmaps.
              </p>
            </div>
          </div>
        </div>

        {/* Dynamic Extract Code Section */}
        <div className="pt-6 border-t border-neutral-200 dark:border-neutral-800 space-y-5">
          <div className="space-y-1">
            <h2 className="text-sm font-bold text-neutral-900 dark:text-white uppercase tracking-wider flex items-center gap-2">
              <FileCode className="w-4 h-4 text-royalblue-500" />
              <span>Extract Code &amp; Export Notebook</span>
            </h2>
            <p className="text-xs text-neutral-500 dark:text-neutral-400">
              Download structured code configurations directly matching your active project parameters to run and scale training on high-performance local clusters or cloud instances.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Jupyter Notebook Card */}
            <div className="bg-white dark:bg-neutral-950 rounded-xl p-5 border border-neutral-150 dark:border-neutral-900 shadow-sm flex flex-col justify-between space-y-4 text-left">
              <div className="space-y-2">
                <div className="flex items-center gap-2">
                  <LayoutTemplate className="w-5 h-5 text-royalblue-500" />
                  <h3 className="text-xs font-bold text-neutral-800 dark:text-neutral-200 uppercase tracking-wider">Jupyter Notebook (.ipynb)</h3>
                </div>
                <p className="text-[11px] text-neutral-500 dark:text-neutral-400 leading-relaxed">
                  Export an interactive notebook containing step-by-step markdown explanations, training loop cell, PyTorch dataset loaders, and model definitions configured in your builder.
                </p>
              </div>
              <button
                onClick={() => downloadFile(notebookJson, `${currentProject.name.toLowerCase().replace(/\s+/g, '_')}_pipeline.ipynb`, 'application/json')}
                className="w-full py-2.5 bg-royalblue-600 hover:bg-royalblue-500 text-white rounded-lg flex items-center justify-center gap-1.5 text-xs font-bold transition-all shadow-sm"
              >
                <Download className="w-3.5 h-3.5" />
                <span>Download Notebook (.ipynb)</span>
              </button>
            </div>

            {/* Python Code Script Card */}
            <div className="bg-white dark:bg-neutral-950 rounded-xl p-5 border border-neutral-150 dark:border-neutral-900 shadow-sm flex flex-col justify-between space-y-4 text-left">
              <div className="space-y-2">
                <div className="flex items-center gap-2">
                  <Code className="w-5 h-5 text-emerald-500" />
                  <h3 className="text-xs font-bold text-neutral-800 dark:text-neutral-200 uppercase tracking-wider">Standalone Python Script (.py)</h3>
                </div>
                <p className="text-[11px] text-neutral-500 dark:text-neutral-400 leading-relaxed">
                  Download a production-grade Python script mapping out the full data transforms, learning rate schedulers, model weight parameters, and optimization pipelines.
                </p>
              </div>
              <div className="flex gap-2">
                <button
                  onClick={copyToClipboard}
                  className="flex-1 py-2.5 bg-neutral-100 dark:bg-neutral-900 hover:bg-neutral-200 dark:hover:bg-neutral-800 text-neutral-700 dark:text-neutral-300 rounded-lg flex items-center justify-center gap-1.5 text-xs font-semibold transition-all border border-neutral-200 dark:border-neutral-800"
                >
                  {copied ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
                  <span>{copied ? 'Copied!' : 'Copy Script'}</span>
                </button>
                <button
                  onClick={() => downloadFile(pytorchScript, `${currentProject.name.toLowerCase().replace(/\s+/g, '_')}_train.py`, 'text/plain')}
                  className="py-2.5 px-4 bg-royalblue-600 hover:bg-royalblue-500 text-white rounded-lg flex items-center justify-center gap-1.5 text-xs font-bold transition-all shadow-sm"
                  title="Download Python Script"
                >
                  <Download className="w-3.5 h-3.5" />
                </button>
              </div>
            </div>
          </div>
        </div>

        {/* Footer Navigation */}
        <div className="pt-6 flex justify-end border-t border-neutral-200 dark:border-neutral-800">
          <button
            onClick={() => router.push('/etl')}
            className="flex items-center gap-2 px-4 py-2.5 bg-royalblue-600 hover:bg-royalblue-500 text-white rounded-lg text-xs font-semibold transition-all group shadow-sm"
          >
            <span>Proceed to Ingestion</span>
            <ArrowRight className="w-3.5 h-3.5 transition-transform group-hover:translate-x-1" />
          </button>
        </div>

      </div>
    </div>
  );
}
